#!/usr/bin/env python3
"""Generates data/bundle.js — an offline snapshot of manifest + all pages.

Lets index.html work when opened via file:// (double-click), where browsers
block fetch() of local JSON. The bundle is ONLY loaded on file:; served
copies (GitHub Pages, serve.bat) always fetch live JSON.

GENERATED ARTIFACT — never edit bundle.js by hand. Re-run this script after
any change to data/manifest.json or data/pages/*.json:
    python tools/build-bundle.py
"""
import json, os
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
m = json.load(open(os.path.join(root, 'data/manifest.json'), encoding='utf-8'))
pages = {}
for s in m['sections']:
    for p in s['pages']:
        entries = [p] + p.get('children', [])
        for e in entries:
            pid = e['id']
            pages[pid] = json.load(open(os.path.join(root, 'data', e['file']), encoding='utf-8'))
bundle = {'manifest': m, 'pages': pages}
out = os.path.join(root, 'data/bundle.js')
with open(out, 'w', encoding='utf-8') as f:
    f.write('/* GENERATED by tools/build-bundle.py — do not edit. Offline (file://) snapshot. */\n')
    f.write('window._BUNDLE = ')
    json.dump(bundle, f, ensure_ascii=False, separators=(',', ':'))
    f.write(';\n')
print(f"bundle.js: {os.path.getsize(out)} bytes, {len(pages)} pages")
